[release]
auto_version = false
always_commit_message = false
create_tag = true
push = true

[homebrew]
enabled = true

formula="Formula/q-tip.rb"
repository="./homebrew-q-tip"

commit_message = "Update Q-Tip to {version}"
push = true
